version: '3.5'

services:
  api1:
    image: api1
    hostname: api1
    expose:
      - "8080"
    build: ../
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  api2:
    image: api2
    hostname: api2
    expose:
      - "8080"
    build: ../
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M