version: '3.5'

services:
  api1:
    image: api1
    hostname: api1
    expose:
      - "8080"
    build: ../
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  api2:
    image: api2
    hostname: api2
    expose:
      - "8080"
    build: ../
    depends_on:
      - db
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  db:
    image: postgres
    hostname: db
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    #volumes:
     # - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: person
      POSTGRES_PASSWORD: person
      POSTGRES_DB: person
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'