version: '3.9'

services:
  api1:
    image: api1
    hostname: api1
    environment:
      - SERVER_PORT=8081
      - DATABASE_URL=jdbc:postgresql://localhost:5432/person
      - DATABASE_USERNAME=person
      - DATABASE_PASSWORD=person
    expose:
      - "8081"
    build: ../
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 1.0GB
    restart: always
    network_mode: host

  api2:
    image: api2
    hostname: api2
    environment:
      - SERVER_PORT=8082
      - DATABASE_URL=jdbc:postgresql://localhost:5432/person
      - DATABASE_USERNAME=person
      - DATABASE_PASSWORD=person
    expose:
      - "8082"
    build: ../
    depends_on:
      - db
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 1.0GB
    restart: always
    network_mode: host

  nginx:
    image: nginx
    hostname: nginx
    extra_hosts:
      - "docker.for.mac.host.internal:host-gateway"
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    network_mode: host

  db:
    image: postgres
    hostname: db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: person
      POSTGRES_PASSWORD: person
      POSTGRES_DB: person
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500M'
    network_mode: host