version: '3.9'

services:
  api1:
    image: api1
    hostname: api1
    environment:
      - SERVER_PORT=8081
      - DATABASE_URL=jdbc:postgresql://localhost:5432/person
      - DATABASE_USERNAME=person
      - DATABASE_PASSWORD=person
    build: ../
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 1GB
    restart: always
    network_mode: host

  api2:
    image: api2
    hostname: api2
    environment:
      - SERVER_PORT=8082
      - DATABASE_URL=jdbc:postgresql://localhost:5432/person
      - DATABASE_USERNAME=person
      - DATABASE_PASSWORD=person
    expose:
      - "8082"
    build: ../
    depends_on:
      - db
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 1GB
    restart: always
    network_mode: host

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 300M
    network_mode: host
    depends_on:
      - api1

  db:
    image: postgres
    hostname: db
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: person
      POSTGRES_PASSWORD: person
      POSTGRES_DB: person
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500M'